# Generated by Django 2.2.16 on 2020-10-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_usage_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='API usage type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cms_technology_platform',
            field=models.CharField(blank=True, max_length=50, verbose_name='CMS/Technology platform'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commercial',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Non-Commercial', 'Non-Commercial')], max_length=50, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='heard_about',
            field=models.CharField(blank=True, max_length=250, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation_address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organisation address (line 1)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation_address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organisation address (line 2)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation_address3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organisation address (line 3)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation_type_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Organisation Type (if other selected)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation_url',
            field=models.URLField(blank=True, verbose_name='Organisation Website'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_level',
            field=models.CharField(choices=[('General User', 'General User'), ('Offline Application User', 'Offline Application User'), ('Partner', 'Partner'), ('Unlimited', 'Unlimited')], max_length=50, verbose_name='User Level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website_using_api',
            field=models.URLField(verbose_name='Website that will use the API'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP/Postal Code'),
        ),
    ]
